<?php 
$ex=Etc::findfirst();
echo $this->flashSession->output(); 
?>
<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">   
    <form name="formUser" action="" method="post">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">ID :</label>
          <div class="col-sm-10">
          <?php echo $ex->n_id ?>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Title :</label>
          <div class="col-sm-10">
            <input class="form-control" id="title" name="title" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Artist_name :</label>
          <div class="col-sm-10">
            <input class="form-control" id="artist" name="artist" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Year :</label>
          <div class="col-sm-10">
            <input class="form-control" id="year" name="year" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Description :</label>
          <div class="col-sm-10">
            <input class="form-control" id="description" name="description" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Type :</label>
          <div class="col-sm-10">
            <input class="form-control" id="type" name="type" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Epoch :</label>
          <div class="col-sm-10">
            <input class="form-control" id="epoch" name="epoch" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Origin :</label>
          <div class="col-sm-10">
            <input class="form-control" id="origin" name="origin" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Collcection_name :</label>
          <div class="col-sm-10">
            <input class="form-control" id="collcection" name="collcection" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm"></label>
          <div class="col-sm-10">
              <input type="file" class="form-control custom-file-input" name="file" id="file">
              <label class="custom-file-label" for="file" accept="image/*">Choose picture</label>
          </div>
        </div>
        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Add">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>
 </form>