<?php 
$id=$this->session->get('id');
echo $this->flashSession->output(); 
?>

<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">     
    <form name="formUser" action="" method="post">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">ID :</label>
          <div class="col-sm-10">
            <input class="form-control" id="id" name="id" value="<?php echo $id;?>" required="" type="text">         
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Type :</label>
          <div class="col-sm-10">
            <input class="form-control" id="start" name="start" value="" required="" type="date">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Darwn_on :</label>
          <div class="col-sm-10">
            <input class="form-control" id="end" name="end" value="" required="" type="date">
          </div>
        </div>
        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Add">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>
 </form>   