<?php 
$name=$this->session->get('name');
?>

<table data-toggle="table" class="table">
    <thead>
        <tr>
            <td><a href="<?php echo $this->url->getBaseUri().'admin/aArt' ?>" class="btn btn-danger navbar-btn">Art</a></td>
            <td><a href="<?php echo $this->url->getBaseUri().'admin/aArtist' ?>" class="btn btn-danger navbar-btn">Artist</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/aCollection' ?>" class="btn btn-danger navbar-btn">Collection</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/aExhibition' ?>" class="btn btn-danger navbar-btn">Exhibition</a></td>
            <td><a href="<?php echo $this->url->getBaseUri().'admin/aGeneral' ?>" class="btn btn-danger navbar-btn">General</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/aGuide' ?>" class="btn btn-danger navbar-btn">Guide</a></td> 
        </tr>
    </thead>
</table>      