<?php 
$name=$this->session->get('name');
$act=Collection::findfirst("name = '$name'");
echo $this->flashSession->output(); 
?>

<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">     
    <form name="formUser" action="" method="post">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Name :</label>
          <div class="col-sm-10">
            <input class="form-control" id="name" name="name" value="<?php echo $act->name;?>" required="" type="text">         
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Phone :</label>
          <div class="col-sm-10">
            <input class="form-control" id="phone" name="phone" value="<?php echo $act->phone;?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Address :</label>
          <div class="col-sm-10">
            <input class="form-control" id="address" name="address" value="<?php echo $act->address;?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Description :</label>
          <div class="col-sm-10">
            <input class="form-control" id="description" name="description" value="<?php echo $act->description;?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Type :</label>
          <div class="col-sm-10">
            <input class="form-control" id="type" name="type" value="<?php echo $act->type;?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Contact_person :</label>
          <div class="col-sm-10">
            <input class="form-control" id="person" name="person" value="<?php echo $act->contact_person;?>" required="" type="text">
          </div>
        </div>
        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Add">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>
 </form>   