<?php 
$name=$this->session->get('name');
?>

<table data-toggle="table" class="table">
    <thead>
        <tr>
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SdArt' ?>" class="btn btn-danger navbar-btn">Art</a></td>
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SdArtist' ?>" class="btn btn-danger navbar-btn">Artist</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SdCollection' ?>" class="btn btn-danger navbar-btn">Collection</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SdExhibition' ?>" class="btn btn-danger navbar-btn">Exhibition</a></td>
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SdGeneral' ?>" class="btn btn-danger navbar-btn">General</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SdGuide' ?>" class="btn btn-danger navbar-btn">Guide</a></td> 
        </tr>
    </thead>
</table>      