<?php 
$id=$this->session->get('id');
$ex=Borrowed::findfirst("id_no = '$id'");
echo $this->flashSession->output(); 
?>

<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">     
    <form name="formUser" action="" method="post">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">ID :</label>
          <div class="col-sm-10">
          <?php echo $id ?>         
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Start :</label>
          <div class="col-sm-10">
            <input class="form-control" id="start" name="start" value="<?php echo $ex->date_borrowed ?>" required="" type="date">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">End :</label>
          <div class="col-sm-10">
            <input class="form-control" id="end" name="end" value="<?php echo $ex->date_returned ?>" required="" type="date">
          </div>
        </div>
        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Add">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>
 </form>   