<?php 
$name=$this->session->get('name');
?>

<table data-toggle="table" class="table">
    <thead>
        <tr>
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SeArt' ?>" class="btn btn-danger navbar-btn">Art</a></td>
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SeArtist' ?>" class="btn btn-danger navbar-btn">Artist</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SeCollection' ?>" class="btn btn-danger navbar-btn">Collection</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SeExhibition' ?>" class="btn btn-danger navbar-btn">Exhibition</a></td>
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SeGeneral' ?>" class="btn btn-danger navbar-btn">General</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/SeGuide' ?>" class="btn btn-danger navbar-btn">Guide</a></td> 
        </tr>
    </thead>
</table>      