<?php 
$name=$this->session->get('name');
$act=Exhibition::findfirst("name = '$name'");
echo $this->flashSession->output(); 
?>

<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">     
    <form name="formUser" action="" method="post">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Name :</label>
          <div class="col-sm-10">
            <input class="form-control" id="name" name="name" value="<?php echo $act->name;?>" required="" type="text">         
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Start :</label>
          <div class="col-sm-10">
            <input class="form-control" id="start" name="start" value="<?php echo $act->start_date;?>" required="" type="date">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">End :</label>
          <div class="col-sm-10">
            <input class="form-control" id="end" name="end" value="<?php echo $act->end_date;?>" required="" type="date">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Number :</label>
          <div class="col-sm-10">
            <input class="form-control" id="number" name="number" value="<?php echo $act->number_of_people;?>" required="" type="text">
          </div>
        </div>
        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Add">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>
 </form>   