<?php 
$id=$this->session->get('id');
$act=Guide_service::findfirst("guide_id = '$id'");
echo $this->flashSession->output(); 
?>

<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">     
    <form name="formUser" action="" method="post">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">ID :</label>
          <div class="col-sm-10">
          <?php echo $act->guide_id ?>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Name :</label>
          <div class="col-sm-10">
            <input class="form-control" id="name" name="name" value="<?php echo $act->name;?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Rating :</label>
          <div class="col-sm-10">
            <input class="form-control" id="rating" name="rating" value="<?php echo $act->rating;?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Time :</label>
          <div class="col-sm-10">
            <input class="form-control" id="time" name="time" value="<?php echo $act->time;?>" required="" type="text">
          </div>
        </div>
        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Add">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>
 </form>   