<?php 
$id=$this->session->get('id');
$ex=Permanent_collection::findfirst("id_no = '$id'");
echo $this->flashSession->output(); 
?>


<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">     
    <form name="formUser" action="" method="post">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">ID :</label>
          <div class="col-sm-10">
          <?php echo $id ?>         
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Cost :</label>
          <div class="col-sm-10">
            <input class="form-control" id="cost" name="cost" value="<?php echo $ex->cost ?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Status :</label>
          <div class="col-sm-10">
            <input class="form-control" id="status" name="status" value="<?php echo $ex->status ?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">date_acquired :</label>
          <div class="col-sm-10">
            <input class="form-control" id="get" name="get" value="<?php echo $ex->date_acquired ?>" required="" type="date">
          </div>
        </div>
        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Update">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>
 </form>  