<?php 
$id=$this->session->get('id');
$ex=Sculpture::findfirst("art_no = '$id'");
echo $this->flashSession->output(); 
?>

<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">     
    <form name="formUser" action="" method="post">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">ID :</label>
          <div class="col-sm-10">
          <?php echo $id ?>         
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Material :</label>
          <div class="col-sm-10">
            <input class="form-control" id="material" name="material" value="<?php echo $ex->material ?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Height :</label>
          <div class="col-sm-10">
            <input class="form-control" id="height" name="height" value="<?php echo $ex->height ?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Weight :</label>
          <div class="col-sm-10">
            <input class="form-control" id="weight" name="weight" value="<?php echo $ex->weight ?>" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Style :</label>
          <div class="col-sm-10">
            <input class="form-control" id="style" name="style" value="<?php echo $ex->style ?>" required="" type="text">
          </div>
        </div>
        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Update">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>
 </form>