<?php 
$name=$this->session->get('name');
?>

<table data-toggle="table" class="table">
    <thead>
        <tr>
            <td><a href="<?php echo $this->url->getBaseUri().'admin/add' ?>" class="btn btn-danger navbar-btn">Add</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/edit' ?>" class="btn btn-danger navbar-btn">Update</a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'admin/delete' ?>" class="btn btn-danger navbar-btn">Delete</a></td> 
        </tr>
    </thead>
</table>      