<?php 
$name=$this->session->get('name');
?>

<table data-toggle="table" class="table">
    <tbody>
        <?php foreach($data as $item){?>
            <tr>
  
            </tr>
            <?php echo $item->title ?>
            <div class="form-group">  
            <img style="width:100px; height:100px" src="<?php echo $this->url->getBaseUri().'public/img/database/'.$item->picture; ?>">
            </div>    
                               
        <?php } ?>
    </tbody>
    
</table>      