
<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">   
    <form name="formUser" action="" method="post">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Visit_id :</label>
          <div class="col-sm-10">
            <input class="form-control" id="id" name="id" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Date :</label>
          <div class="col-sm-10">
            <input class="form-control" id="day" name="day" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Admission_fees :</label>
          <div class="col-sm-10">
          <?php echo "200" ?>
          </div>
        </div>
        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Buy Now">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>
 </form>
<?php 
echo $this->flashSession->output(); 
?>