
<table data-toggle="table" class="table">
    <thead>
        <tr>
            <td><a href="<?php echo $this->url->getBaseUri().'ticket/Admission' ?>" class="btn btn-danger navbar-btn"><?php echo 'Admission' ?></a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'ticket/Exhibition' ?>" class="btn btn-danger navbar-btn"><?php echo 'Exhibition' ?></a></td> 
        </tr>
    </thead>
</table>      