<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Phalcon PHP Framework</title>
    <?php echo $this->assets->outputCss('styles'); ?>    
    <?php echo $this->assets->outputJs('scripts'); ?>
  </head>
    <body id="page-top" >
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
      <div id="logo">
            <a href="#page-top"><img src="img/logo.png" alt="" title="" /></a>
            </div>
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link text-white py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>index">Home</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link text-white py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>art">Art_Object</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link text-white py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>exhibition">Exhibition</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link text-white py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>collection">Collection</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link text-white py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>ticket">Ticket</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link text-white py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>guide">Guide</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link text-white py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>artist">Artist</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link text-white py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>profile"><?php echo $this->session->get('memberEmail');?></a>
            </li>
          </ul>
           <ul class="navbar-nav  navbar-right">    
    <?php if($this->session->has('memberAuthen')) {?>
      <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link text-white py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>admin">Admin</a>
            </li>
   
     
     <li class="nav-item mx-0 mx-lg-1">
            <a  class="btn btn-danger navbar-btn" href="authen/signOut"> Logout </a>
     </li>  
    <?php } else {?>
      <li class="nav-item mx-0 mx-lg-1">
       <a href="authen" class="btn btn-outline-primary"> Login </a>
      </li>    
     <li class="nav-item mx-0 mx-lg-1">
       <a href="authen/signUp" class="btn btn-outline-info"> Sign Up </a>
      </li>
      
      <?php }?>
    </ul>
        </div>
      </div>
    </nav>
 
    <!-- Header -->
   
    <header class="masthead bg-primary text-white">
       <div class="container"><?php echo $this->getContent(); ?></div>      
    </header>
 
   
    <!-- Footer -->  
 
    <div class="copyright py-4 text-center text-black">
      <div class="container">
        <small>ART MUSEUM &copy; CPE25</small>
      </div>
    </div>
 
  </body>
 
</html>
<?php 
echo $this->flashSession->output(); 
?>