
<table data-toggle="table" class="table">
    <thead>
        <tr>
            <td><a href="<?php echo $this->url->getBaseUri().'art/type?name=Painting' ?>" class="btn btn-danger navbar-btn"><?php echo 'Painting' ?></a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'art/type?name=Sculpture' ?>" class="btn btn-danger navbar-btn"><?php echo 'Sculpture' ?></a></td> 
            <td><a href="<?php echo $this->url->getBaseUri().'art/type?name=Other' ?>" class="btn btn-danger navbar-btn"><?php echo 'Other' ?></a></td> 
        </tr>
    </thead>
</table>      