<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
<div class="container">
        <div style="font-family: 'Tangerine', serif;" align=Center>
       <font size=6 color=#000000>Welcome To Our</font><br><font size=11 color=#000000>Art Museum</font>
       </div>
       <div align=Right>
       <embed src="http://www.clocklink.com/clocks/0031-black.swf?TimeZone=ICT&"  width="230" height="230" wmode="transparent" type="application/x-shockwave-flash"></embed>
      <br> <embed type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" name="flashplayer" src="http://i251.photobucket.com/albums/gg294/wafpaf/calendars/swf/fun1.swf" quality="high" width="260" height="210" swliveconnect="true" allowscriptaccess="samedomain" /></embed><br>
      </div>
</div>