<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">     
    <form name="formUser" action="" method="post">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">ชื่อกิจกรรม :</label>
          <div class="col-sm-10">
            <input class="form-control" id="id" name="id" value="" required="" type="text">
            <div class="invalid-feedback">
              Please fill data.
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">วันที่ :</label>
          <div class="col-sm-10">
            <input class="form-control" id="epoch" name="epoch" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">วันที่ :</label>
          <div class="col-sm-10">
            <input class="form-control" id="name" name="name" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">รายละเอียด :</label>
          <div class="col-sm-10">
            <input class="form-control" id="origin" name="origin" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">ชื่อกิจกรรม :</label>
          <div class="col-sm-10">
            <input class="form-control" id="description" name="description" value="" required="" type="text">
            <div class="invalid-feedback">
              Please fill data.
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">วันที่ :</label>
          <div class="col-sm-10">
            <input class="form-control" id="title" name="title" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">รายละเอียด :</label>
          <div class="col-sm-10">
            <input class="form-control" id="type" name="type" value="" required="" type="text">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm"></label>
          <div class="col-sm-10">
              <input type="file" class="form-control custom-file-input" name="file" id="file">
              <label class="custom-file-label" for="file" accept="image/*">Choose picture</label>
          </div>
        </div>
        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Add">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>
 </form>